name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # package-lock.json이 저장소에 있어야 npm ci 성공
      - name: Install deps
        run: npm ci

      # Secrets → .env 파일 생성
      - name: Create .env
        run: |
          cat > .env <<EOF
          VITE_FB_API_KEY=${{ secrets.VITE_FB_API_KEY }}
          VITE_FB_AUTH_DOMAIN=${{ secrets.VITE_FB_AUTH_DOMAIN }}
          VITE_FB_DATABASE_URL=${{ secrets.VITE_FB_DATABASE_URL }}
          VITE_FB_PROJECT_ID=${{ secrets.VITE_FB_PROJECT_ID }}
          VITE_FB_STORAGE_BUCKET=${{ secrets.VITE_FB_STORAGE_BUCKET }}
          VITE_FB_MESSAGING_SENDER_ID=${{ secrets.VITE_FB_MESSAGING_SENDER_ID }}
          VITE_FB_APP_ID=${{ secrets.VITE_FB_APP_ID }}
          EOF

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
